### PR TITLE
Upgrade Reqwest to 12.0 

### PR DESCRIPTION
**Pull request by Sagebati**

### CODE REVIEW

**Review by baraknaveh — APPROVED** [review]
Looks good!

**Comment by baraknaveh** [comment]
@jpopesculian if not too much trouble, would be great if you can merge and release this to unblock https://github.com/64bit/async-openai/pull/204. Thanks!

**Comment by jpopesculian** [comment]
Thanks!!!

**Comment by baraknaveh** [comment]
Thank you!

**Pull request merged**
